### ISSUE TITLE
Extraction information

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/Identification#4]
Peux tu extraire de la base SSO un fichier Excel avec les colonnes
Nom    Prénom    Société    adresse mail

**Comment by Portekoi** [comment]
Qu'est ce que la base SSO? Je pense pouvoir le faire si j'ai cette info.

**Comment by AlainPierreSDPV** [comment]
le SSO c’est le serveur d’autorisation  qui permet d'acceder aux applications des 3 franchises de coservices qui sont :   Clovis Location -  SDPV et trucksplus ci dessous le lien que j'utilise pour gérer les personnes dont je suis le référent 
http://id.coservices.fr/UserReseau/ReferentTree.aspx

**Comment by MamboJoel** [comment]
Elle a pour nom "Identification" dans SQL Server et observe le pattern de tables Microsoft d'authentification. Je ne suis pas particulièrement familier avec ce pattern, si tu peux faire l'extraction d'Alain c'est bien. Quel champ veux-tu Alain ?

**Comment by Portekoi** [comment]
Je sais pas si cela répond à la demande. J'ai mis les colonnes demandées plus une notion de "level" pour visualiser le niveau de chaque utilisateur.
[SSO.xlsx](https://github.com/groupe-gac/Identification/files/768824/SSO.xlsx)

Dites moi si cela vous convient.

**Comment by AlainPierreSDPV** [comment]
Merci Damien cela me convient parfaitement
